name: example_app
description: "A basic weather app using the Bloc pattern and Dio for API calls."
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  dio: 5.8.0+1
  flutter_bloc: 9.1.0
  pretty_dio_logger: 1.4.0
  
  equatable: 2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  mockito: 5.4.5

flutter:

  uses-material-design: true

  assets:
    - assets\icons\drawable-hdpi\ic_loading.png
    - assets\icons\drawable-xhdpi\ic_loading.png
    - assets\icons\drawable-mdpi\ic_loading.png
    - assets\icons\drawable-xxhdpi\ic_loading.png
    - assets\icons\drawable-xxxhdpi\ic_loading.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
