name: example_app
description: "A basic weather app using the Bloc pattern and Dio for API calls."
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  #flavor
  flavor: 2.0.0
  
  #state management
  flutter_bloc: 9.1.0
  equatable: 2.0.7

  #api 
  dio: 5.8.0+1
  pretty_dio_logger: 1.4.0

  #ui
  cupertino_icons: 1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  mockito: 5.4.5
  flutter_launcher_icons: 0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets\icons\drawable-hdpi\ic_loading.png
    - assets\icons\drawable-xhdpi\ic_loading.png
    - assets\icons\drawable-mdpi\ic_loading.png
    - assets\icons\drawable-xxhdpi\ic_loading.png
    - assets\icons\drawable-xxxhdpi\ic_loading.png


  fonts:
    - family: Roboto
      fonts:
        - asset: assets\fonts\Roboto-Regular.ttf
        - asset: assets\fonts\Roboto-Black.ttf
        - asset: assets\fonts\Roboto-Thin.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
